---

version: '3.2'

# Local environment should mount plaintext files as secrets
secrets:
  DJANGO_DB_NAME:
    file: ./secrets/DJANGO_DB_NAME
  DJANGO_DB_USER:
    file: ./secrets/DJANGO_DB_USER
  DJANGO_DB_PASSWORD:
    file: ./secrets/DJANGO_DB_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/MYSQL_ROOT_PASSWORD
  SECRET_KEY:
    file: ./secrets/SECRET_KEY
  TWLIGHT_OAUTH_CONSUMER_KEY:
    file: ./secrets/TWLIGHT_OAUTH_CONSUMER_KEY
  TWLIGHT_OAUTH_CONSUMER_SECRET:
    file: ./secrets/TWLIGHT_OAUTH_CONSUMER_SECRET
  TWLIGHT_EZPROXY_SECRET:
    file: ./secrets/TWLIGHT_EZPROXY_SECRET

services:
  db:
    # Local environment should accomodate a variety of host OSes
    volumes:
      - type: bind
        source: ./conf/db/local.d
        target: /etc/mysql/conf.d
  twlight:
    image: wikipedialibrary/twlight:branch_${TRAVIS_BRANCH}
    build:
      cache_from:
        - wikipedialibrary/twlight_base:branch_${TRAVIS_BRANCH}
        - wikipedialibrary/twlight_build:branch_${TRAVIS_BRANCH}
        - wikipedialibrary/twlight:branch_${TRAVIS_BRANCH}
    env_file:
      - ./conf/travis.twlight.env
    environment:
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - COVERALLS_REPO_TOKEN
    # Local environment should mount things from the code directory
    volumes:
      - type: bind
        source: .
        target: /app
  web:
    volumes:
      - type: bind
        source: ./conf/local.nginx.conf
        target: /etc/nginx/conf.d/default.conf
